// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Antd = require("antd");
var React = require("react");

function Demo(Props) {
  return React.createElement("div", undefined, "Hello!", React.createElement(Antd.Select, { }));
}

var make = Demo;

exports.make = make;
/* antd Not a pure module */
