// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Demo(Props) {
  return React.createElement("div", undefined, "Hello!");
}

var make = Demo;

exports.make = make;
/* react Not a pure module */
